# -*- coding: utf-8 -*-
"""ShubhaNandhini(ibmtask3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xhBJWC86PJKFmza-cyqoCEEgrWwbOomf
"""

s = "Hi there Sam!"

s = "Hi there Sam!"
x=s.split()
x

planet = "Earth"
diameter = 12742

planet="Earth"
diameter=12742
print(f"the diameter of {planet} is {diameter} Kilometers.")

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

import numpy as np

import numpy as np
np.zeros(10)

import numpy as np
x=np.ones(10)*5
print(x)

import numpy as np
x=np.arange(20,35)
y=(x%2==0)
z=x[y]
print(z)

import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr=np.concatenate((a,b))
print(arr)

import pandas as pd

import pandas as pd
lists = [['ajay', 22], ['santhosh', 25], ['ram', 24]]
df=pd.DataFrame(lists,columns=['name','age'],dtype=int)
df

from datetime import date,timedelta
sdate=date(2023,1,1)
edate=date(2023,2,10)
delta=edate-sdate
for i in range(delta.days+1):
 day=sdate+timedelta(days=i)
 print(day)

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['sno','name','age'],dtype=int)
df